version: '2'

services:

  postgis:
    image: kartoza/postgis:9.5-2.2
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /home/geomatik/1/postgres_data:/var/lib/postgresql
    environment:
     - POSTGRES_USER=geomatik
     - POSTGRES_PASS=geomatik
     - ALLOW_IP_RANGE=0.0.0.0/0

  lizmap:
    image: jancelin/docker-lizmap:3.1-2.14LTR
    restart: always
    ports:
      - 80:80
    volumes:
      - /home/geomatik/1/lizmap/lizmap_project:/home
      - /home/geomatik/1/lizmap/lizmap_var:/var/www/websig/lizmap/var
      
  rstudio:
    image: rocker/rstudio
    restart: always
    ports:
      - 8787:8787
    links:
      - postgis
    volumes:
      - /home/geomatik/1/rstudio:/home/geomatik
    environment:
      - USER=geomatik
      - PASSWORD=geomatik

  owncloud:
    image: owncloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - "/home/geomatik/1/owncloud/apps:/var/www/html/apps"
      - "/home/geomatik/1/owncloud/config:/var/www/html/config"
      - "/home/geomatik/1/owncloud/data:/var/www/html/data"
  mysql:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: geomatik
      
 gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    ports:
      - 90:80
      - 443:443
      - 25:22
    volumes:
      - '/home/geomatik/1/gitlab/config:/etc/gitlab'
      - '/home/geomatik/1/gitlab/logs:/var/log/gitlab'
      - '/home/geomatik/1/gitlab/data:/var/opt/gitlab'
          
# https://hub.docker.com/_/owncloud/
# ownCloud with MariaDB/MySQL
#
# Access via "http://localhost:8080" (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial ownCloud setup, select "Storage & database" --> "Configure the database" --> "MySQL/MariaDB"
# Database user: root
# Database password: geomatik
# Database name: geomatik
# Database host: replace "localhost" with "mysql"


