version: '2'

services:

  qgis2web1:
    image: apache1
    restart: always
    ports:
      - 8081:80
    volumes:
      - "/home/geomatik/1/qgis2web/:/var/www/html/"

  qgis2web2:
    image: apache1
    restart: always
    ports:
      - 8082:80
    volumes:
      - "/home/geomatik/1/qgis2web1/:/var/www/html/"
